version: 1.0.0
apiVersion: v2
name: minter-explorer-web
icon: https://explorer.minter.network/img/minter-logo-circle.svg
description: A Helm chart for Minter Explorer Web

appVersion: v1.0.0

home: https://github.com/MinterTeam/minter-explorer-web
keywords:
  - minter
  - explorer
maintainers:
  - name: shrpne
    email: shrpne@gmail.com

