version: '3.6'

services:
  app:
    build: ./
    ports:
      -  ${EXPLORER_WEB_PORT}:80
    environment:
      APP_ENV: ${APP_ENV}
      APP_EXPLORER_API_URL: ${APP_EXPLORER_API_URL}
      APP_EXPLORER_RTM_URL: ${APP_EXPLORER_RTM_URL}
